# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article', verbose_name='\u8bc4\u8bba\u6587\u7ae0'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='\u8bc4\u8bba\u5185\u5bb9'),
        ),
    ]
