# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_article_comment_nums'),
        ('operation', '0002_auto_20171126_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('tag_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Article', verbose_name='\u6587\u7ae0\u6807\u7b7e')),
            ],
        ),
    ]
