# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_name',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
