# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_article_comment_nums'),
        ('operation', '0004_auto_20171128_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(default='', max_length=20, verbose_name='\u6807\u7b7e\u540d')),
                ('article', models.ManyToManyField(to='index.Article')),
            ],
        ),
    ]
