# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
