# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20171128_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='\u8bc4\u8bba\u8005\u90ae\u7bb1'),
        ),
    ]
