# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-26 06:30
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
    ]
