# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20171128_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletotag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articletotag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ArticleToTag',
        ),
    ]
