# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20171128_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='index.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
