# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20171128_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default='', max_length=600, verbose_name='\u6458\u8981'),
        ),
    ]
